[workspace]
resolver = "3"
members = [
    "crates/snek-shared",
    "crates/snek-relay",
    "crates/snek-client",
]

[workspace.dependencies]
snek-shared = { path = "crates/snek-shared" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
futures-util = "0.3"
uuid = { version = "1", features = ["v4", "serde"] }
rand = "0.10.0"
color-eyre = "0.6.5"
